spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workdb
    username: postgres
    password: dhtvtyf
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    root: info
    com.work: info
  file:
    name: work.log
    path: /